version: '3'

networks:
  kong_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.36.0.0/24

services:
  grpcurl:
    image: networld/grpcurl:latest
    container_name: grpcurl
    restart: on-failure
    networks:
      - kong_net
  consul:
    image: consul
    container_name: consul
    restart: on-failure
    ports:
      - 8500:8500
    networks:
      kong_net:
        ipv4_address: 172.36.0.10

  kong-database:
    image: postgres:9.6
    container_name: kong-database
    networks:
      kong_net:
        ipv4_address: 172.36.0.11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"

  kong-migrations:
    image: kong:2.1.4
    networks:
      - kong_net
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - kong-database

  kong:
    image: kong:2.1.4
    networks:
      - kong_net
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=172.36.0.11
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:9080 http2
      - KONG_DNS_RESOLVER=172.36.0.10:8600
      - KONG_DNS_ORDER=SRV,LAST,A,CNAME
    restart: on-failure
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 9080:9080
    links:
      - kong-database:kong-database
      - consul:consul
    depends_on:
      - kong-migrations

  grpc-golang-one:
    image: golang:latest
    networks:
      - kong_net
    restart: on-failure
    container_name: grpc-golang-one
    links:
      - consul:consul
    tty: true
  grpc-golang-two:
    image: golang:latest
    networks:
      - kong_net
    restart: on-failure
    container_name: grpc-golang-two
    links:
      - consul:consul
    tty: true

  konga:
    image: pantsel/konga
    networks:
      - kong_net
    ports:
      - 1337:1337
    links:
      - kong:kong
    container_name: konga
    environment:
      - NODE_ENV=production

volumes:
  db-data-kong-postgres:

